{{ if not .Values.content.metadataOptions }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "apimap.name" .}}-content-configmap
data:
  metadata-options.json: |
    {
      "fileOptions": {
        "version": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ]
      },
      "apiOptions": {
        "visibilityOptions":[
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ]
      },
      "apiVersionOptions": {
        "releaseStatusOptions": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ]
      },
      "organizationOptions": {
        "architectureLayerOptions": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ],
        "businessUnitOptions": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ]
      },
      "implementationDetailsOptions": {
        "interfaceSpecificationImplementationOptions": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ],
        "interfaceSpecificationSpecificationOptions": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ],
        "interfaceDescriptionLanguageOptions": [
          {
            "label": "Content Missing",
            "value": "Content Missing",
            "description": "Content Missing",
            "filter": "Content Missing"
          }
        ]
      }
    }
{{ end }}