apiVersion: v1
kind: Service
metadata:
  name: {{ template "apimap.name" .}}-service
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apimap.name" .}}-developer
spec:
  {{ if .Values.exposure.nodePort.enabled }}
  type: NodePort
  {{ else }}
  type: ClusterIP
  {{ end }}
  ports:
    {{ if .Values.exposure.nodePort.enabled }}
    - name: http
      port: 80
      targetPort: {{ template "apimap.targetPort" .}}
    - name: https
      port: 443
      targetPort: {{ template "apimap.targetPort" .}}
    {{ end }}
    {{ if .Values.exposure.ingress.enabled }}
    - name: https
      port: {{ template "apimap.targetPort" . }}
      targetPort: {{ template "apimap.targetPort" . }}
    {{ end }}
  selector:
    app: {{ template "apimap.name" .}}-developer
