# metadata to be appended to each API response
metadata:
  # copyright notice of the company that owns this installment and the contained data
  copyright: ""
  # faq URL to view more about the catalog install
  faq: ""
  # support channel link to where users of the catalog can get help
  support: ""
# storage of the content include in the catalog
storage:
  # nitrite enables the catalog to be completely self-contained including the data storage
  nitrite:
    # persistence volume path
    path: "/var/apimap"
    # enabled nitrite support
    enabled: true
# log level
log:
  # service log level definition
  level: INFO
openapi:
  enabled: true