# metadata to be appended to each API response
metadata:
  # copyright notice of the company that owns this installment and the contained data
  copyright: ""
  # faq URL to view more about the catalog install
  faq: ""
  # support channel link to where users of the catalog can get help
  support: ""
# storage of the content include in the catalog
storage:
  # nitrite enables the catalog to be completely self-contained including the data storage
  nitrite:
    # persistence volume path
    path: "/var/apimap"
    # enabled nitrite support
    enabled: false
    # storage class to be used
    storageClass: ""
  # mongodb enables use of a dedicated db solution
  mongodb:
    # enabled mongodb support
    enabled:  true
    # database name to be used
    databaseName: "apimap"
    # An encrypted connection string to be used
    uri:
      # name of the secret to be inserted
      secretName: ""
      # name of the secret key to be used
      secretKey: ""
# log level
log:
  # service log level definition
  level: INFO
  # Management / Statistics endpoints
  endpoints:
    statistics:
      enabled: false
    health:
      enabled: false
# OpenApi specification
openapi:
  # Enabled OpenApi specification endpoint to all users
  enabled: false
# Exposure Configuration
exposure:
  # NodePort Configuration
  nodePort:
    # Enable nodeport
    enabled: false
  # Ingress Configuration
  ingress:
    # Enable ingress
    enabled: true
    # Hostname to be used
    host: ""
# Resources to be used when running the system
resources:
  # pods configuration
  pods:
    # Replicas of the code to be run
    replicas: 2