{{- if .Values.storage.mongodb.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apimap.name" .}}-deployment
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "apimap.name" .}}-api
    role: api
    supplier: apimap.io
spec:
  replicas: {{ .Values.resources.pods.replicas }}
  selector:
    matchLabels:
      app: {{ template "apimap.name" .}}-api
  template:
    metadata:
      labels:
        app: {{ template "apimap.name" .}}-api
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
    spec:
      containers:
        - name: {{ template "apimap.name" .}}-api
          image: {{ template "apimap.image" }}
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: {{ template "apimap.targetPort" .}}
            - name: https
              containerPort: {{ template "apimap.targetPort" . }}
          env:
            - name: SPRING_APPLICATION_JSON
              valueFrom:
                configMapKeyRef:
                  name: {{ template "apimap.name" .}}-configmap
                  key: config.json
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  key: {{ .Values.storage.mongodb.uri.secretKey }}
                  name: {{ .Values.storage.mongodb.uri.secretName }}
{{ end }}