{{- if .Values.storage.nitrite.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "apimap.name" .}}-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
{{- end -}}