apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "apimap.name" .}}-deployment
  labels:
    app: {{ template "apimap.name" .}}-portal
    role: frontend
    supplier: apimap.io
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "apimap.name" .}}-portal
  template:
    metadata:
      labels:
        app: {{ template "apimap.name" .}}-portal
        role: frontend
    spec:
      volumes:
        - name: metadata-options
          configMap:
            name: {{ if .Values.content.metadataOptions }}{{ .Values.content.metadataOptions }}{{- else }}{{ template "apimap.name" .}}-content-configmap{{- end }}
            items:
              - key: metadata-options.json
                path: metadata-options.json
      containers:
        - name: {{ template "apimap.name" .}}-portal
          image: apimap/portal:1.0.0
          imagePullPolicy: Always
          ports:
            - name: public
              containerPort: {{ template "apimap.targetPort" . }}
          volumeMounts:
            - name: metadata-options
              mountPath: /app/dist/content/metadata-options.json
              subPath: metadata-options.json
          env:
            - name: "API_URL"
              value: {{ .Values.urls.api }}
            - name: "DEVELOPER_URL"
              value: {{ .Values.urls.developer }}
            - name: "TITLE"
              value: {{ .Values.branding.title }}