apiVersion: v1
kind: Service
metadata:
  name: {{ template "apimap.name" .}}-service
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: {{ template "apimap.targetPort" .}}
    - name: https
      port: 443
      targetPort: {{ template "apimap.targetPort" .}}
  selector:
    app: {{ template "apimap.name" .}}-portal
