name: Chart Lint
on:
  push:
    branches:
      - main
      - 'feature/**'
  pull_request:
    branches:
      - main
      - 'feature/**'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.4.0
      - name: Run apimap-api chart-testing (lint)
        run: helm lint charts/apimap-api/
      - name: Run apimap-api chart-testing (lint)
        run: helm lint charts/apimap-portal/